#!/bin/python3

import smtplib
import sys


# import the corresponding modules
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

port = 587
smtp_server = "smtp-mail.outlook.com"
login = "quest_lab@outlook.com" # paste your login generated by Mailtrap
password = "quest123" # paste your password generated by Mailtrap

subject = "Hammer Session Run Data"
sender_email = "quest_lab@outlook.com"
receiver_email = "mkumar46@wisc.edu"

message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

# Add body to email
body = "Body of the Mail"
message.attach(MIMEText(body, "plain"))

filename = sys.argv[1]
# Open PDF file in binary mode

# We assume that the file is in the directory where you run your Python script from
with open(filename, "rb") as attachment:
    # The content type "application/octet-stream" means that a MIME attachment is a binary file
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode to base64
encoders.encode_base64(part)

# Add header 
part.add_header(
    "Content-Disposition",
    f"attachment; filename= {filename}",
)

# Add attachment to your message and convert it to string
message.attach(part)
text = message.as_string()

# send your email
with smtplib.SMTP("smtp-mail.outlook.com", 587) as server:
    server.connect("smtp-mail.outlook.com", 587)
    server.starttls()
    server.login(login, password)
    server.sendmail(
        sender_email, receiver_email, text
    )
print('Sent')
